targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/**
      source_gen:combining_builder:
        enabled: true

